spring:
  application:
    name: capstone

  datasource:
    url: jdbc:postgresql://localhost:5424/capstone_db
    driver-class-name: org.postgresql.Driver
    username: acc_dev
    password: acc_dev12

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
