ALTER TABLE widget
    DROP CONSTRAINT fk_widget_on_user;

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE widget
    ADD CONSTRAINT FK_WIDGET_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

DROP TABLE "user" CASCADE;

DROP SEQUENCE user_seq CASCADE;

DROP SEQUENCE widget_seq CASCADE;

CREATE SEQUENCE IF NOT EXISTS widget_id_seq;
ALTER TABLE widget
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE widget
    ALTER COLUMN id SET DEFAULT nextval('widget_id_seq');

ALTER SEQUENCE widget_id_seq OWNED BY widget.id;